version: '3.9'
services:
  app:
    image: simple-go-rest-api
    container_name: simple-go-rest-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: app-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres